<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Bill_book extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bill_book_model');
    }
    
    /*
     * Listing of bill_book
     */
    function index()
    {
        $data['bill_book'] = $this->Bill_book_model->get_all_bill_book();
        $this->load->view('bill_book/index',$data);
    }
    
    /*
     * Adding new bill_book
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('general_details_id','General Details Id','integer');
		$this->form_validation->set_rules('reg_date','Reg Date','required');
		$this->form_validation->set_rules('reg_no','Reg No','required|max_length[255]');
		$this->form_validation->set_rules('owner','Owner','required|max_length[255]');
		$this->form_validation->set_rules('manufacturer','Manufacturer','required|max_length[255]');
		$this->form_validation->set_rules('model','Model','required|max_length[255]');
		$this->form_validation->set_rules('manufacturing_year','Manufacturing Year','required|max_length[255]');
		$this->form_validation->set_rules('no_of_cylinder','No Of Cylinder','required|max_length[255]');
		$this->form_validation->set_rules('engine_capacity_cc','Engine Capacity Cc','required|integer');
		$this->form_validation->set_rules('chasis_no','Chasis No','required|max_length[255]');
		$this->form_validation->set_rules('engine_no','Engine No','required|max_length[255]');
		$this->form_validation->set_rules('loading_capacity','Loading Capacity','integer');
		$this->form_validation->set_rules('fuel_used','Fuel Used','required|max_length[255]');
		$this->form_validation->set_rules('use','Use','required|max_length[255]');
		$this->form_validation->set_rules('reg_validity_date','Reg Validity Date','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'reg_date' => $this->input->post('reg_date'),
				
                'reg_date_nep' => $this->input->post('reg_date_nep'),
                                'vehicle_no' => $this->input->post('vehicle_no'),
				'reg_no' => $this->input->post('reg_no'),
				'owner' => $this->input->post('owner'),
				'manufacturer' => $this->input->post('manufacturer'),
				'model' => $this->input->post('model'),
				'manufacturing_year' => $this->input->post('manufacturing_year'),
				'no_of_cylinder' => $this->input->post('no_of_cylinder'),
				'engine_capacity_cc' => $this->input->post('engine_capacity_cc'),
				'chasis_no' => $this->input->post('chasis_no'),
				'engine_no' => $this->input->post('engine_no'),
				'loading_capacity' => $this->input->post('loading_capacity'),
				'fuel_used' => $this->input->post('fuel_used'),
				'radio' => $this->input->post('radio'),
				'use' => $this->input->post('use'),
				'reg_validity_date' => $this->input->post('reg_validity_date'),
				'reg_validity_date_nep' => $this->input->post('reg_validity_date_nep'),
				'remarks' => $this->input->post('remarks'),
				'od_or_tp' => $this->input->post('od_or_tp'),
            );
            
            $bill_book_id = $this->Bill_book_model->add_bill_book($params);
            redirect('details/index/'.$this->input->post('general_details_id'));
        }
        else
        {
            $data['general_details_id']= $this->uri->segment(3);
            $data['od_or_tp']= $this->uri->segment(4);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('bill_book/add',$data);
            $this->load->view('includes/footer.php');
        }
    }
    
    /*
     * Editing bill_book
     */
    function edit($bill_book_id)
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('general_details_id','General Details Id','integer');
		$this->form_validation->set_rules('reg_date','Reg Date','required');
		$this->form_validation->set_rules('reg_no','Reg No','required|max_length[255]');
		$this->form_validation->set_rules('owner','Owner','required|max_length[255]');
		$this->form_validation->set_rules('manufacturer','Manufacturer','required|max_length[255]');
		$this->form_validation->set_rules('model','Model','required|max_length[255]');
		$this->form_validation->set_rules('manufacturing_year','Manufacturing Year','required|max_length[255]');
		$this->form_validation->set_rules('no_of_cylinder','No Of Cylinder','required|max_length[255]');
		$this->form_validation->set_rules('engine_capacity_cc','Engine Capacity Cc','required|integer');
		$this->form_validation->set_rules('chasis_no','Chasis No','required|max_length[255]');
		$this->form_validation->set_rules('engine_no','Engine No','required|max_length[255]');
		$this->form_validation->set_rules('loading_capacity','Loading Capacity','integer');
		$this->form_validation->set_rules('fuel_used','Fuel Used','required|max_length[255]');
		//$this->form_validation->set_rules('radio','Radio','required');
		$this->form_validation->set_rules('use','Use','required|max_length[255]');
		$this->form_validation->set_rules('reg_validity_date','Reg Validity Date','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'reg_date' => $this->input->post('reg_date'),
		'reg_date_nep' => $this->input->post('reg_date_nep'),
						
                'reg_no' => $this->input->post('reg_no'),
				'owner' => $this->input->post('owner'),
				'manufacturer' => $this->input->post('manufacturer'),
				'vehicle_no' => $this->input->post('vehicle_no'),
				'model' => $this->input->post('model'),
				'manufacturing_year' => $this->input->post('manufacturing_year'),
				'no_of_cylinder' => $this->input->post('no_of_cylinder'),
				'engine_capacity_cc' => $this->input->post('engine_capacity_cc'),
				'chasis_no' => $this->input->post('chasis_no'),
				'engine_no' => $this->input->post('engine_no'),
				'loading_capacity' => $this->input->post('loading_capacity'),
				'fuel_used' => $this->input->post('fuel_used'),
				'radio' => $this->input->post('radio'),
				'use' => $this->input->post('use'),
				'reg_validity_date' => $this->input->post('reg_validity_date'),
		'reg_validity_date_nep' => $this->input->post('reg_validity_date_nep'),
						
                'remarks' => $this->input->post('remarks'),
				'od_or_tp' => $this->input->post('od_or_tp'),
            );

            $this->Bill_book_model->update_bill_book($bill_book_id,$params);            
            redirect('details/index/'.$params['general_details_id'].'#od');
        }
        else
        {   
            $data['bill_book'] = $this->Bill_book_model->get_bill_book($bill_book_id);
            $data['general_details_id']= $this->uri->segment(3);
            $data['od_or_tp']= $this->uri->segment(4);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('bill_book/edit',$data);
            $this->load->view('includes/footer.php');
        }
    }
    
    /*
     * Deleting bill_book
     */
    function remove($bill_book_id, $general_details_id)
    {
        $this->Bill_book_model->delete_bill_book($bill_book_id);
        redirect('details/index/'.$general_details_id);
    }
}
