<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Driving_licence extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Driving_licence_model');
    }
    
    /*
     * Listing of driving_licence
     */
    function index()
    {
        $data['driving_licence'] = $this->Driving_licence_model->get_all_driving_licence();
        $this->load->view('driving_licence/index',$data);
    }
    
    /*
     * Adding new driving_licence
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		$this->form_validation->set_rules('address','Address','required|max_length[255]');
		$this->form_validation->set_rules('licence_no','Licence No','required|max_length[255]');
		$this->form_validation->set_rules('licence_date','Licence Date','required');
		$this->form_validation->set_rules('type_of_licence','Type Of Licence','required|max_length[255]');
		$this->form_validation->set_rules('driving_authority','Driving Authority','max_length[255]');
		$this->form_validation->set_rules('validity_date','Validity Date','required');
		$this->form_validation->set_rules('issued_zone','Issued Zone','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'name' => $this->input->post('name'),
				'address' => $this->input->post('address'),
				'licence_no' => $this->input->post('licence_no'),
				'licence_date' => $this->input->post('licence_date'),
                                'licence_date_nep' => $this->input->post('licence_date_nep'),
                                'type_of_licence' => $this->input->post('type_of_licence'),
				'driving_authority' => $this->input->post('driving_authority'),
				'validity_date' => $this->input->post('validity_date'),
				'validity_date_nep' => $this->input->post('validity_date_nep'),
				'issued_zone' => $this->input->post('issued_zone'),
				'remarks' => $this->input->post('remarks'),
				'od_or_tp' => $this->input->post('od_or_tp'),
            );
            
            $driving_licence_id = $this->Driving_licence_model->add_driving_licence($params);
            redirect('details/index/'.$this->input->post('general_details_id'));
        }
        else
        {
            $data['general_details_id']= $this->uri->segment(3);
            $data['od_or_tp']= $this->uri->segment(4);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('driving_licence/add',$data);
            $this->load->view('includes/footer.php');
        }
    }
    
    /*
     * Editing driving_licence
     */
    function edit($driving_licence_id)
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		$this->form_validation->set_rules('address','Address','required|max_length[255]');
		$this->form_validation->set_rules('licence_no','Licence No','required|max_length[255]');
		$this->form_validation->set_rules('licence_date','Licence Date','required');
		$this->form_validation->set_rules('type_of_licence','Type Of Licence','required|max_length[255]');
		$this->form_validation->set_rules('driving_authority','Driving Authority','max_length[255]');
		$this->form_validation->set_rules('validity_date','Validity Date','required');
		$this->form_validation->set_rules('issued_zone','Issued Zone','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'name' => $this->input->post('name'),
				'address' => $this->input->post('address'),
				'licence_no' => $this->input->post('licence_no'),
				'licence_date' => $this->input->post('licence_date'),
				'licence_date_nep' => $this->input->post('licence_date_nep'),
				'type_of_licence' => $this->input->post('type_of_licence'),
				'driving_authority' => $this->input->post('driving_authority'),
				'validity_date' => $this->input->post('validity_date'),
				'validity_date_nep' => $this->input->post('validity_date_nep'),
				'issued_zone' => $this->input->post('issued_zone'),
				'remarks' => $this->input->post('remarks'),
				'od_or_tp' => $this->input->post('od_or_tp'),
            );

            $this->Driving_licence_model->update_driving_licence($driving_licence_id,$params);            
            redirect('details/index/'.$this->input->post('general_details_id'));
        }
        else
        {   
            $data['driving_licence'] = $this->Driving_licence_model->get_driving_licence($driving_licence_id);
            $data['general_details_id']= $this->uri->segment(3);
            $data['od_or_tp']= $this->uri->segment(4);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('driving_licence/edit',$data);
            $this->load->view('includes/footer.php');
        }
    }
    
    /*
     * Deleting driving_licence
     */
    function remove($driving_licence_id, $general_details_id)
    {
        $this->Driving_licence_model->delete_driving_licence($driving_licence_id);
        redirect('details/index/'.$general_details_id);
}
}
