<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Field_assessment extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Field_assessment_model');
    }
    
    /*
     * Listing of field_assessment
     */
    function index()
    {
        $data['field_assessment'] = $this->Field_assessment_model->get_all_field_assessment();
        $this->load->view('field_assessment/index',$data);
    }
    
    /*
     * Adding new field_assessment
     */




    function add()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
                
		$this->form_validation->set_rules('date_of_visit','Date Of Visit','');
		$this->form_validation->set_rules('estimated_loss','Estimated Loss','integer');
		//$this->form_validation->set_rules('date_of_second_visit','Date of Second Visit','required');
		//$this->form_validation->set_rules('details_of_accident','Details Of Accident','required');
		//$this->form_validation->set_rules('photos','Photos','required');
		//$this->form_validation->set_rules('scheduled_next_visit','Scheduled Next Visit','required');
		//$this->form_validation->set_rules('status_of_file_id','Status Of File Id','required|integer');
		$generalid=$data['general_details_id']= $this->uri->segment(3);		
		$data['case_type']=$this->Field_assessment_model->get_type_by_general_id($generalid);	
		
		//Type OD first field assessment count		
		$data['field_assessment_count']=($this->Field_assessment_model->get_total_number_of_field_assessment($generalid)['cnt']);
		//Type OD second field assessment count		
		$data['second_field_assessment_count']=($this->Field_assessment_model->get_number_of_second_field_assessment($generalid)['cnt']);	
		//print_r($data['second_field_assessment_count']);
		//Type TP first field assessment count
		$data['first_field_assessment_count']=($this->Field_assessment_model->get_total_number_of_field_assessment($generalid)	['cnt']);	
		//print_r($data['first_field_assessment_count']);		
		//this is in field assessment table
		//Type TP second field assessment count
		$data['first_tp_field_assessment_count']=($this->Field_assessment_model->get_total_number_of_tp_field_assessment($generalid)['cnt']);	//this is in field assessment tp table
		//print_r("tp:".$data['first_tp_field_assessment_count']);
			
		$data['second_tp_field_assessment_count']=($this->Field_assessment_model->get_second_tp_field_assessment($generalid)['cnt']);	//this is in field assessment tp table
		//print_r("tpm:".$data['second_tp_field_assessment_count']);
		$data['final_tp_field_assessment_count']=($this->Field_assessment_model->get_final_tp_field_assessment($generalid)['cnt']);	
		$data['od_tp_field_assessment_count_od']=($this->Field_assessment_model->get_od_tp_field_assessment_count_od($generalid)['cnt']);
		$data['od_tp_field_assessment_count_tp']=($this->Field_assessment_model->get_od_tp_field_assessment_count_tp($generalid)['cnt']);
		//$data['first_od_tp_tp_field_assessment_count']=($this->Field_assessment_model->get_first_od_tp_tp_field_assessment_count($generalid)['cnt']);

		print_r("count:".$data['od_tp_field_assessment_count_tp']);

		if($this->form_validation->run() )     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'date_of_visit_nep' => $this->input->post('date_of_visit_nep'),		
                		'date_of_visit' => $this->input->post('date_of_visit'),
			        'date_of_accident' => $this->input->post('date_of_accident'),
                		'date_of_accident_nep' => $this->input->post('date_of_accident_nep'),
				'estimated_loss' => $this->input->post('estimated_loss'),
				'visited_by_uid' => $this->input->post('visited_by_uid'),
				'details_of_accident' => $this->input->post('details_of_accident'),
				'photos' => $this->input->post('photos'),
				'cause' => $this->input->post('cause'),
                		'nature' => $this->input->post('nature'),
				'destination' => $this->input->post('destination'),
				'origin' => $this->input->post('origin'),
                		'place_of_accident' => $this->input->post('place_of_accident')
            );
	          /*  
		$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);
		*/
		
	    $field_assessment_id = $this->Field_assessment_model->add_field_assessment($params);
            	
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {
            $data['general_details_id']= $this->uri->segment(3);
	   
	   
            $data['date_of_accident']=$this->input->post('date_of_accident');
            $data['date_of_accident_nep']=$this->input->post('date_of_accident_nep');
	    
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/add', $data);
            $this->load->view('includes/footer.php');
        }
    }
    

function add_tp_info(){
	$this->load->library('form_validation');
        $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
                
		$this->form_validation->set_rules('date_of_visit','Date Of Visit','');
		$this->form_validation->set_rules('estimated_loss','Estimated Loss','integer');
		//$this->form_validation->set_rules('date_of_second_visit','Date of Second Visit','required');
		//$this->form_validation->set_rules('details_of_accident','Details Of Accident','required');
		//$this->form_validation->set_rules('photos','Photos','required');
		//$this->form_validation->set_rules('scheduled_next_visit','Scheduled Next Visit','required');
		//$this->form_validation->set_rules('status_of_file_id','Status Of File Id','required|integer');
		$generalid=$data['general_details_id']= $this->uri->segment(3);		
		$data['case_type']=$this->Field_assessment_model->get_type_by_general_id($generalid);	
		$data['od_tp_field_assessment_count_tp']=($this->Field_assessment_model->get_od_tp_field_assessment_count_tp($generalid)['cnt']);
		$data['first_od_tp_tp_field_assessment_count']=($this->Field_assessment_model->get_second_od_tp_tp_field_assessment_count($generalid)['cnt']);
		$data['second_od_tp_tp_field_assessment_count']=($this->Field_assessment_model->get_third_od_tp_tp_field_assessment_count($generalid)['cnt']);
		//print_r("count:".$data['od_tp_field_assessment_count_tp']);

		if($this->form_validation->run() )     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'date_of_visit_nep' => $this->input->post('date_of_visit_nep'),		
                		'date_of_visit' => $this->input->post('date_of_visit'),
			        'date_of_accident' => $this->input->post('date_of_accident'),
                		'date_of_accident_nep' => $this->input->post('date_of_accident_nep'),
				'estimated_loss' => $this->input->post('estimated_loss'),
				'visited_by_uid' => $this->input->post('visited_by_uid'),
				'details_of_accident' => $this->input->post('details_of_accident'),
				'photos' => $this->input->post('photos'),
				'cause' => $this->input->post('cause'),
                		'nature' => $this->input->post('nature'),
				'destination' => $this->input->post('destination'),
				'origin' => $this->input->post('origin'),
                		'place_of_accident' => $this->input->post('place_of_accident')
            );
	          /*  
		$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);
		*/
		
	    $field_assessment_id = $this->Field_assessment_model->add_od_tp_field_assessment($params);
            	
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {
            $data['general_details_id']= $this->uri->segment(3);
	   
	   
            $data['date_of_accident']=$this->input->post('date_of_accident');
            $data['date_of_accident_nep']=$this->input->post('date_of_accident_nep');
	    
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/add_tp_info', $data);
            $this->load->view('includes/footer.php');
        }

}




function add_second_tp_visit_details(){
	$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);

	//$this->load->library('form_validation');        
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
	print_r($second_params);
	$this->Field_assessment_model->add_second_od_field_assessment($second_params);
	redirect('index.php/details/index/'.$this->input->post('general_details_id'));
}

function add_final_tp_visit_details(){
	$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_final_visit'=>$this->input->post('date_of_final_visit'),
					'site_of_final_visit'=>$this->input->post('site_of_final_visit'),
					'final_visit_by'=>$this->input->post('final_visit_by')
			);

	//$this->load->library('form_validation');        
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
	//print_r($second_params);
	$this->Field_assessment_model->add_final_od_field_assessment($second_params);
	redirect('index.php/details/index/'.$this->input->post('general_details_id'));
}






 function add_second_od_visit_details(){
	$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);

	//$this->load->library('form_validation');        
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
	print_r($second_params);
	$this->Field_assessment_model->add_second_od_field_assessment($second_params);
	redirect('index.php/details/index/'.$this->input->post('general_details_id'));
}

	function add_final_od_visit_details(){
	$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_final_visit'=>$this->input->post('date_of_final_visit'),
					'site_of_final_visit'=>$this->input->post('site_of_final_visit'),
					'final_visit_by'=>$this->input->post('final_visit_by')
			);

	//$this->load->library('form_validation');        
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
	print_r($second_params);
	$this->Field_assessment_model->add_final_od_field_assessment($second_params);
	redirect('index.php/details/index/'.$this->input->post('general_details_id'));
}

//for cases OD+TP

function add_od_tp_second_tp_visit_details(){
	$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);

	//$this->load->library('form_validation');        
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
	print_r($second_params);
	$this->Field_assessment_model->add_second_tp_field_assessment($second_params);
	redirect('index.php/details/index/'.$this->input->post('general_details_id'));
}

	function add_od_tp_final_tp_visit_details(){
	$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_final_visit'=>$this->input->post('date_of_final_visit'),
					'site_of_final_visit'=>$this->input->post('site_of_final_visit'),
					'final_visit_by'=>$this->input->post('final_visit_by')
			);

	//$this->load->library('form_validation');        
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
	print_r($second_params);
	$this->Field_assessment_model->add_final_tp_field_assessment($second_params);
	redirect('index.php/details/index/'.$this->input->post('general_details_id'));
}



//Add tp vehicle info in  field assessment tp

function add_tp_visit_details()
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
                
		$this->form_validation->set_rules('date_of_visit','Date Of Visit','');
		$this->form_validation->set_rules('estimated_loss','Estimated Loss','integer');
		//$this->form_validation->set_rules('date_of_second_visit','Date of Second Visit','required');
		//$this->form_validation->set_rules('details_of_accident','Details Of Accident','required');
		//$this->form_validation->set_rules('photos','Photos','required');
		//$this->form_validation->set_rules('scheduled_next_visit','Scheduled Next Visit','required');
		//$this->form_validation->set_rules('status_of_file_id','Status Of File Id','required|integer');
		$generalid=$data['general_details_id']= $this->uri->segment(3);		
		$data['case_type']=$this->Field_assessment_model->get_type_by_general_id($generalid);	

		if ($data['case_type']=='Only TP'){
		$data['first_field_assessment_count']=($this->Field_assessment_model->get_total_number_of_field_assessment($generalid)['cnt']);	//this is in field assessment table
		$data['first_tp_field_assessment_count']=($this->Field_assessment_model->get_total_number_of_tp_field_assessment($generalid)['cnt']);	//this is in field assessment tp table
		}





		if($this->form_validation->run() )     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'date_of_visit_nep' => $this->input->post('date_of_visit_nep'),		
                		'date_of_visit' => $this->input->post('date_of_visit'),
			        'date_of_accident' => $this->input->post('date_of_accident'),
                		'date_of_accident_nep' => $this->input->post('date_of_accident_nep'),
				'estimated_loss' => $this->input->post('estimated_loss'),
				'visited_by_uid' => $this->input->post('visited_by_uid'),
				'details_of_accident' => $this->input->post('details_of_accident'),
				'photos' => $this->input->post('photos'),
				'cause' => $this->input->post('cause'),
                		'nature' => $this->input->post('nature'),
				'destination' => $this->input->post('destination'),
				'origin' => $this->input->post('origin'),
                		'place_of_accident' => $this->input->post('place_of_accident')
            );
	          /*  
		$second_params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);
		*/
		
	$field_assessment_id = $this->Field_assessment_model->add_tp_field_assessment($params);
            	
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {
            $data['general_details_id']= $this->uri->segment(3);
	  
            $data['date_of_accident']=$this->input->post('date_of_accident');
            $data['date_of_accident_nep']=$this->input->post('date_of_accident_nep');
    
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/add', $data);
            $this->load->view('includes/footer.php');
        }
    }



//Added
//Added for OD+TP

    function add_tp_details(){
	 $this->load->library('form_validation');
        $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
                
		$this->form_validation->set_rules('date_of_visit','Date Of Visit','');
		$this->form_validation->set_rules('estimated_loss','Estimated Loss','integer');
		//$this->form_validation->set_rules('date_of_second_visit','Date of Second Visit','required');
		//$this->form_validation->set_rules('details_of_accident','Details Of Accident','required');
		//$this->form_validation->set_rules('photos','Photos','required');
		//$this->form_validation->set_rules('scheduled_next_visit','Scheduled Next Visit','required');
		//$this->form_validation->set_rules('status_of_file_id','Status Of File Id','required|integer');
		$generalid=$data['general_details_id']= $this->uri->segment(3);		
		$data['case_type']=$this->Field_assessment_model->get_type_by_general_id($generalid);
		$data['od_tp_field_assessment_count_od']=($this->Field_assessment_model->get_od_tp_field_assessment_count_od($generalid)['cnt']);
		$data['od_tp_field_assessment_count_tp']=($this->Field_assessment_model->get_od_tp_field_assessment_count_tp($generalid)['cnt']);
		if($this->form_validation->run() )     

        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'date_of_visit_nep' => $this->input->post('date_of_visit_nep'),		
                		'date_of_visit' => $this->input->post('date_of_visit'),
			        'date_of_accident' => $this->input->post('date_of_accident'),
                		'date_of_accident_nep' => $this->input->post('date_of_accident_nep'),
				'estimated_loss' => $this->input->post('estimated_loss'),
				'visited_by_uid' => $this->input->post('visited_by_uid'),
				'details_of_accident' => $this->input->post('details_of_accident'),
				'photos' => $this->input->post('photos'),
				'cause' => $this->input->post('cause'),
                		'nature' => $this->input->post('nature'),
				'destination' => $this->input->post('destination'),
				'origin' => $this->input->post('origin'),
                		'place_of_accident' => $this->input->post('place_of_accident')
            );
	$field_assessment_id = $this->Field_assessment_model->add_to_field_assessment_tp($params);
            	
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {
            $data['general_details_id']= $this->uri->segment(3);
	  
            $data['date_of_accident']=$this->input->post('date_of_accident');
            $data['date_of_accident_nep']=$this->input->post('date_of_accident_nep');
    
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/add', $data);
            $this->load->view('includes/footer.php');
        }
}





    /*
     * Editing field_assessment
     */
    function edit($assessment_id)
    {   
        $this->load->library('form_validation');
        $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');

		$this->form_validation->set_rules('date_of_visit','Date Of Visit','required');
		$this->form_validation->set_rules('estimated_loss','Estimated Loss','integer');
		$this->form_validation->set_rules('visited_by_uid','Visited By','required');
		$this->form_validation->set_rules('details_of_accident','Details Of Accident','required');
		$this->form_validation->set_rules('photos','Photos','required');
		$this->form_validation->set_rules('scheduled_next_visit','Scheduled Next Visit','required');
		$this->form_validation->set_rules('status_of_file_id','Status Of File Id','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'general_details_id' => $this->input->post('general_details_id'),
				'date_of_visit' => $this->input->post('date_of_visit'),
		'date_of_visit_nep' => $this->input->post('date_of_visit_nep'),			
                'date_of_accident' => $this->input->post('date_of_accident'),
                'date_of_accident_nep' => $this->input->post('date_of_accident_nep'),
				'estimated_loss' => $this->input->post('estimated_loss'),
				'visited_by_uid' => $this->input->post('visited_by_uid'),
				'details_of_accident' => $this->input->post('details_of_accident'),
				'photos' => $this->input->post('photos'),
				'scheduled_next_visit' => $this->input->post('scheduled_next_visit'),
                 'scheduled_next_visit_nep' => $this->input->post('scheduled_next_visit_nep'),
				'status_of_file_id' => $this->input->post('status_of_file_id'),
				'submission_date' => $this->input->post('submission_date'),
                'submission_date_nep' => $this->input->post('submission_date_nep'),
				'call_notification_date' => $this->input->post('call_notification_date'),
                'call_notification_date_nep' => $this->input->post('call_notification_date_nep'),
				'sms_notification_date' => $this->input->post('sms_notification_date'),
                'sms_notification_date_nep' => $this->input->post('sms_notification_date_nep'),
            );

            $this->Field_assessment_model->update_field_assessment($assessment_id,$params);            
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {   
            $data['field_assessment'] = $this->Field_assessment_model->get_field_assessment($assessment_id);
            $data['general_details_id']= $this->uri->segment(3);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/edit',$data);
            $this->load->view('includes/footer.php');
        }
    }
    
	function edit_second_od_visit_details($assessment_id){
		$this->load->library('form_validation');
                $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
		$this->form_validation->set_rules('date_of_second_visit','Date Of Second Visit','required');
	
		if($this->form_validation->run())     
        {   
            $params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_second_visit'=>$this->input->post('date_of_second_visit'),
					'site_of_second_visit'=>$this->input->post('site_of_second_visit'),
					'second_visit_by'=>$this->input->post('second_visit_by')
			);

            $this->Field_assessment_model->update_second_od_field_assessment($assessment_id,$params);            
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {   
            $data['second_od_field_assessment_info'] = $this->Field_assessment_model->get_second_od_field_assessment_by_assessmentId($assessment_id);
            $data['general_details_id']= $this->uri->segment(3);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/edit_second_od',$data);
            $this->load->view('includes/footer.php');
        }
	//$this->load->library('form_validation');
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
}


	function edit_final_od_visit_details($assessment_id){
		$this->load->library('form_validation');
                $this->form_validation->set_error_delimiters('<div class="text-danger">', '</div>');
		$this->form_validation->set_rules('date_of_final_visit','Date Of Second Visit','required');
	
		if($this->form_validation->run())     
        {   
            $params= array(
					'general_details_id' => $this->input->post('general_details_id'),
					'date_of_final_visit'=>$this->input->post('date_of_final_visit'),
					'site_of_final_visit'=>$this->input->post('site_of_final_visit'),
					'final_visit_by'=>$this->input->post('final_visit_by')
			);

            $this->Field_assessment_model->update_final_od_field_assessment($assessment_id,$params);            
            redirect('index.php/details/index/'.$this->input->post('general_details_id'));
        }
        else
        {   
            $data['field_assessment'] = $this->Field_assessment_model->get_final_od_field_assessment_by_assessmentId($assessment_id);
            $data['general_details_id']= $this->uri->segment(3);
            $this->load->view('includes/header.php');
            $this->load->view('includes/sidebar.php');
            $this->load->view('field_assessment/edit_final_od',$data);
            $this->load->view('includes/footer.php');
        }
	//$this->load->library('form_validation');
	//$this->form_validation->set_rules('date_of_second_visit','Date Of Visit','required');
}


    /*
     * Deleting field_assessment
     */
    function remove($assessment_id, $general_details_id)
    {
        $this->Field_assessment_model->delete_field_assessment($assessment_id);
        
        redirect('index.php/details/index/'.$general_details_id);
    }

    function remove_second_visit($assessment_id, $general_details_id)
    {
        $this->Field_assessment_model->delete_second_field_assessment($assessment_id);
        
        redirect('index.php/details/index/'.$general_details_id);
    }

    function remove_final_visit($assessment_id, $general_details_id)
    {
        $this->Field_assessment_model->delete_final_field_assessment($assessment_id);
        
        redirect('index.php/details/index/'.$general_details_id);
    }
}
