<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Insurer_lu extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Insurer_lu_model');
    }
    
    /*
     * Listing of insurer_lu
     */
    function index()
    {
        $data['insurer_lu'] = $this->Insurer_lu_model->get_all_insurer_lu();
        $this->load->view('insurer_lu/index',$data);
    }
    
    /*
     * Adding new insurer_lu
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('insurer_name','Insurer Name','required|max_length[255]');
		$this->form_validation->set_rules('insurer_location','Insurer Location','required|integer');
		$this->form_validation->set_rules('insurer_abbr','Insurer Abbr','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'insurer_name' => $this->input->post('insurer_name'),
				'insurer_location' => $this->input->post('insurer_location'),
				'insurer_abbr' => $this->input->post('insurer_abbr'),
            );
            
            $insurer_lu_id = $this->Insurer_lu_model->add_insurer_lu($params);
            redirect('insurer_lu/index');
        }
        else
        {
            $this->load->view('insurer_lu/add');
        }
    }
    
    /*
     * Editing insurer_lu
     */
    function edit($insurer_id)
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('insurer_name','Insurer Name','required|max_length[255]');
		$this->form_validation->set_rules('insurer_location','Insurer Location','required|integer');
		$this->form_validation->set_rules('insurer_abbr','Insurer Abbr','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'insurer_name' => $this->input->post('insurer_name'),
				'insurer_location' => $this->input->post('insurer_location'),
				'insurer_abbr' => $this->input->post('insurer_abbr'),
            );

            $this->Insurer_lu_model->update_insurer_lu($insurer_id,$params);            
            redirect('insurer_lu/index');
        }
        else
        {   
            $data['insurer_lu'] = $this->Insurer_lu_model->get_insurer_lu($insurer_id);
            $this->load->view('insurer_lu/edit',$data);
        }
    }
    
    /*
     * Deleting insurer_lu
     */
    function remove($insurer_id)
    {
        $this->Insurer_lu_model->delete_insurer_lu($insurer_id);
        redirect('insurer_lu/index');
    }
}
