<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class User extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    }
    
    /*
     * Listing of user
     */
    function index()
    {
        $data['user'] = $this->User_model->get_all_user();
        $this->load->view('user/index',$data);
    }
    
    /*
     * Adding new user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('username','Username','required|max_length[255]');
		$this->form_validation->set_rules('password','Password','required|max_length[255]');
		$this->form_validation->set_rules('full_name','Full Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'username' => $this->input->post('username'),
				'password' => $this->input->post('password'),
				'full_name' => $this->input->post('full_name'),
				'admin_flag' => $this->input->post('admin_flag'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
            $this->load->view('user/add');
        }
    }
    
    /*
     * Editing user
     */
    function edit($user_id)
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('username','Username','required|max_length[255]');
		$this->form_validation->set_rules('password','Password','required|max_length[255]');
		$this->form_validation->set_rules('full_name','Full Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'username' => $this->input->post('username'),
				'password' => $this->input->post('password'),
				'full_name' => $this->input->post('full_name'),
				'admin_flag' => $this->input->post('admin_flag'),
            );

            $this->User_model->update_user($user_id,$params);            
            redirect('user/index');
        }
        else
        {   
            $data['user'] = $this->User_model->get_user($user_id);
            $this->load->view('user/edit',$data);
        }
    }
    
    /*
     * Deleting user
     */
    function remove($user_id)
    {
        $this->User_model->delete_user($user_id);
        redirect('user/index');
    }
}
