<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Bill_book_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get bill_book by bill_book_id
     */
    function get_bill_book($bill_book_id)
    {
        return $this->db->get_where('bill_book',array('bill_book_id'=>$bill_book_id))->row_array();
    }
    
    function get_bill_book_by_generalid($generalid)
    {
        return $this->db->get_where('bill_book',array('general_details_id'=>$generalid))->result_array();
    }
    
    function get_bill_book_by_generalid_od($generalid)
    {
        return $this->db->get_where('bill_book',array('general_details_id'=>$generalid, 'od_or_tp'=>0))->result_array();
    }
    
     function get_bill_book_by_generalid_tp($generalid)
    {
        return $this->db->get_where('bill_book',array('general_details_id'=>$generalid, 'od_or_tp'=>1))->result_array();
    }
    /*
     * get all bill_book
     */
    function get_all_bill_book()
    {
        return $this->db->get('bill_book')->result_array();
    }
    
    /*
     * function to add bill_book
     */
    function add_bill_book($params)
    {
        $this->db->insert('bill_book',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bill_book
     */
    function update_bill_book($bill_book_id,$params)
    {
        $this->db->where('bill_book_id',$bill_book_id);
        $this->db->update('bill_book',$params);
    }
    
    /*
     * function to delete bill_book
     */
    function delete_bill_book($bill_book_id)
    {
        $this->db->delete('bill_book',array('bill_book_id'=>$bill_book_id));
    }
    
        
}
