<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Insurer_lu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get insurer_lu by insurer_id
     */
    function get_insurer_lu($insurer_id)
    {
        return $this->db->get_where('insurer_lu',array('insurer_id'=>$insurer_id))->row_array();
    }
    
    /*
     * get all insurer_lu
     */
    function get_all_insurer_lu()
    {
        $this->db->order_by("insurer_name", "asc"); 
        return $this->db->get('insurer_lu')->result_array();
    }
    
    /*
     * function to add insurer_lu
     */
    function add_insurer_lu($params)
    {
        $this->db->insert('insurer_lu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update insurer_lu
     */
    function update_insurer_lu($insurer_id,$params)
    {
        $this->db->where('insurer_id',$insurer_id);
        $this->db->update('insurer_lu',$params);
    }
    
    /*
     * function to delete insurer_lu
     */
    function delete_insurer_lu($insurer_id)
    {
        $this->db->delete('insurer_lu',array('insurer_id'=>$insurer_id));
    }
}
