<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Other_details_cv_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get other_details_cv by other_details_id
     */
    function get_other_details_cv($other_details_id)
    {
        return $this->db->get_where('other_details_cv',array('other_details_id'=>$other_details_id))->row_array();
    }
    
    function get_other_details_cv_by_generalid($generalid)
    {
        return $this->db->get_where('other_details_cv',array('general_details_id'=>$generalid))->result_array();
    }
    
    /*
     * get all other_details_cv
     */
    function get_all_other_details_cv()
    {
        return $this->db->get('other_details_cv')->result_array();
    }
    
    /*
     * function to add other_details_cv
     */
    function add_other_details_cv($params)
    {
        $this->db->insert('other_details_cv',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update other_details_cv
     */
    function update_other_details_cv($other_details_id,$params)
    {
        $this->db->where('other_details_id',$other_details_id);
        $this->db->update('other_details_cv',$params);
    }
    
    /*
     * function to delete other_details_cv
     */
    function delete_other_details_cv($other_details_id)
    {
        $this->db->delete('other_details_cv',array('other_details_id'=>$other_details_id));
    }
}
