<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Policy_paper_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get policy_paper by policy_id
     */
    function get_policy_paper($policy_id)
    {
        return $this->db->get_where('policy_paper',array('policy_id'=>$policy_id))->row_array();
    }
    
    function get_policy_paper_by_generalid($generalid)
    {
        return $this->db->get_where('policy_paper',array('general_details_id'=>$generalid))->result_array();
    }
    
     function get_policy_paper_by_generalid_od($generalid)
    {
        return $this->db->get_where('policy_paper',array('general_details_id'=>$generalid, 'od_or_tp'=>0))->result_array();
    }
    
     function get_policy_paper_by_generalid_tp($generalid)
    {
        return $this->db->get_where('policy_paper',array('general_details_id'=>$generalid, 'od_or_tp'=>1))->result_array();
    }
    
    /*
     * get all policy_paper
     */
    function get_all_policy_paper()
    {
        return $this->db->get('policy_paper')->result_array();
    }
    
    /*
     * function to add policy_paper
     */
    function add_policy_paper($params)
    {
        $this->db->insert('policy_paper',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update policy_paper
     */
    function update_policy_paper($policy_id,$params)
    {
        $this->db->where('policy_id',$policy_id);
        $this->db->update('policy_paper',$params);
    }
    
    /*
     * function to delete policy_paper
     */
    function delete_policy_paper($policy_id)
    {
        $this->db->delete('policy_paper',array('policy_id'=>$policy_id));
    }
}
