<?php
/* 
 * Generated by CRUDigniter v1.3 Beta 
 * www.crudigniter.com
 */
 
class Report_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get reports by report_id
     */
    function get_reports($report_id)
    {
        return $this->db->get_where('reports',array('report_id'=>$report_id))->row_array();
    }
    
    function get_reports_by_generalid($generalid)
    {
        return $this->db->get_where('reports',array('general_details_id'=>$generalid))->result_array();
    }
    
    /*
     * get all reports
     */
    function get_all_reports()
    {
        return $this->db->get('reports')->result_array();
    }
    
    /*
     * function to add reports
     */
    function add_reports($params)
    {
        $this->db->insert('reports',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reports
     */
    function update_reports($report_id,$params)
    {
        $this->db->where('report_id',$report_id);
        $this->db->update('reports',$params);
    }
    
    /*
     * function to delete reports
     */
    function delete_reports($report_id)
    {
        $this->db->delete('reports',array('report_id'=>$report_id));
    }
}
